import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Silkscreen } from "next/font/google";
import { Noto_Serif } from "next/font/google";
import { Barlow_Condensed } from "next/font/google";
import { Cormorant_Garamond } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const silkscreen = Silkscreen({
  variable: "--font-silkscreen",
  subsets: ["latin"],
  weight: ["400"],
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
  weight: ["100"],
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-serif",
  subsets: ["latin"],
  weight: ["100"],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${silkscreen.variable} ${notoSerif.variable} ${barlowCondensed.variable} ${cormorantGaramond.variable} bg-gray-400 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
